#pragma once 

#define TAPPING_TERM 150

#define TAPPING_TOGGLE 2


#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

#undef  ENCODERS_PAD_A
#undef  ENCODERS_PAD_B

#define ENCODERS_PAD_A { B5 }
#define ENCODERS_PAD_B { B6 }

#define ENCODER_RESOLUTION 2